# Computer vision with OpenCV

เนื้อหาประกอบด้วย ดังนี้
1. Basic Image Representation with OpenCV
2. Image Annotation
3. Image Manipulation

---

## 1. Basic Image Representation with OpenCV

In [1]:
# ตรวจสอบเวอร์ชั่นของ OpenCV ที่ติดตั้งไปแล้ว
import cv2
print(cv2.__version__)

4.7.0


### image

In [6]:
# Load an image
image = cv2.imread("lenna.png")

In [7]:
# Print image infomation as is
print(image)

[[[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 ...

 [[ 60  18  84]
  [ 60  18  84]
  [ 58  27  92]
  ...
  [ 84  73 173]
  [ 76  68 172]
  [ 79  62 177]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]]


In [3]:
# Show image properties
print(f'The size of the Image is: {image.shape}')
print(f'The data type of the Image is: {image.dtype}')
print(f'The dimensions of the Image is: {image.ndim}')

The size of the Image is: (512, 512, 3)
The data type of the Image is: uint8
The dimensions of the Image is: 3


In [4]:
# Display image
cv2.imshow("display",image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
# Read image pixel at x=100,y=100 then print to screen
print(image[100,100])

[ 78  68 178]


In [8]:
# Edit pixel in ROI (Region of Interest), y from 50 to 100 and x from 30 to 60 ให้เป็นสีดำ
image[50:100,30:60] = 0

# Show edited image
cv2.imshow("display",image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
# Edit pixel area
image[50:100,50:100] = 0

# Show edited image
cv2.imshow("display",image)

# Save edited image to disk
cv2.imwrite("result.png",image)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Video

#### - load video แล้วแสดงหน้าต่าง

In [10]:
import cv2

# load video จาก webcam
cap = cv2.VideoCapture(0) 

while cap.isOpened():
    ret, frame = cap.read()

    if not ret:
        print("Can't receive frame (stream end?).")
        break

    cv2.imshow('frame', frame)

    if cv2.waitKey(1) == ord('q'): # กด q เพื่อออก
        break
    
cv2.waitKey(0) # จะค้างไว้ frame สุดท้าย รอจนกว่าจะกดปุ่ม q
# Release everything if job is finished
cap.release() # ปล่อยไฟล์ vdo ออกจาก memory
cv2.destroyAllWindows() # ทำลายหน้าต่างทั้งหมดที่ openCV จองไว้

In [12]:
# load video จาก Video file
cap = cv2.VideoCapture('road3.mp4') 

while cap.isOpened():
    ret, frame = cap.read()

    if not ret:
        print("Can't receive frame (stream end?).")
        break

    cv2.imshow('frame', frame)

    if cv2.waitKey(1) == ord('q'): # กด q เพื่อออก
        break
    
#cv2.waitKey(0) # จะค้างไว้ frame สุดท้าย รอจนกว่าจะกดปุ่ม q
# Release everything if job is finished
cap.release() # ปล่อยไฟล์ vdo ออกจาก memory
cv2.destroyAllWindows() # ทำลายหน้าต่างทั้งหมดที่ openCV จองไว้

#### - save video 

In [15]:
# load video จาก Video file
cap = cv2.VideoCapture("road3.mp4")

# Define the codec and create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'XVID') # format vdo
out = cv2.VideoWriter('output.mp4', 
                      fourcc, 
                      20.0, # ใช้เวลาหรือขนาดเท่าไร
                      (256, 256))

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print("Can't receive frame (stream end?).")
        break
        
    frame = cv2.flip(frame, 0) # flip vdo
    
    # write the flipped frame
    out.write(frame)
    cv2.imshow('frame', frame)
    
    if cv2.waitKey(1) == ord('q'):  # กด q เพื่อออก
        break
        
# Release everything if job is finished
cap.release()
out.release()
cv2.destroyAllWindows()    

## 2. Image Annotation

### Basic draw operation

### - Draw rectangle

In [16]:
import cv2

img = cv2.imread('lenna.png')

# Display Image
cv2.imshow('Original Image',img)

# make a copy of the original image
imageRectangle = img.copy()
# define the starting and end points of the rectangle
start_point =(300,115)
end_point =(475,225)
# draw the rectangle
cv2.rectangle(imageRectangle, start_point, end_point, (0, 0, 255), thickness= 3, lineType=cv2.LINE_8) 
# display the output
cv2.imshow('imageRectangle', imageRectangle)
cv2.waitKey(0)

-1

### - Draw circle

In [17]:
import cv2

img = cv2.imread('lenna.png')

# Display Image
cv2.imshow('Original Image',img)

# Make a copy of image
imageCircle = img.copy()
# define the center of circle
circle_center = (415,190)
# define the radius of the circle
radius = 100
#  Draw a circle using the circle() Function
cv2.circle(imageCircle, circle_center, radius, (0, 0, 255), thickness=3, lineType=cv2.LINE_AA) 
# Display the result
cv2.imshow("Image Circle",imageCircle)

cv2.waitKey(0)

-1

### - Draw line

In [18]:
import cv2

img = cv2.imread('lenna.png')

# Display Image
cv2.imshow('Original Image',img)
imageLine = img.copy()

#Draw the image from point A to B
pointA = (200,80)
pointB = (450,80)
cv2.line(imageLine, pointA, pointB, (255, 255, 0), thickness=3, lineType=cv2.LINE_AA)
cv2.imshow('Image Line', imageLine)

cv2.waitKey(0)

-1

### - Draw Text

In [19]:
import cv2

img = cv2.imread('lenna.png')

# Display Image
cv2.imshow('Original Image',img)

# make a copy of the original image
imageText = img.copy()
#let's write the text you want to put on the image
text = 'Hello OpenCV'
#org: Where you want to put the text
org = (50,350)
# write the text on the input image
cv2.putText(imageText, text, org, fontFace = cv2.FONT_HERSHEY_COMPLEX, fontScale = 1.5, color = (250,225,100))
# display the output image with text over it
cv2.imshow("Image Text",imageText)
cv2.waitKey(0)
cv2.destroyAllWindows()

### - Fill polygon

In [20]:
import cv2
import numpy as np

img = cv2.imread('lenna.png')

# Display Image
cv2.imshow('Original Image',img)

# make a copy of the original image
imagePoly = img.copy()

penta = np.array([[[40,160],[120,100],[200,160],[160,240],[80,240]]], np.int32)
triangle = np.array([[[240, 130], [380, 230], [190, 280]]], np.int32)

cv2.polylines(imagePoly, [triangle], True, (0,255,0), thickness=3)
cv2.polylines(imagePoly, [penta], True, (255,120,255),3)
cv2.imshow('imagePoly', imagePoly)
cv2.waitKey(0)

-1

## 3. Image Manipulation

### Arithmetic operations on images

In [24]:
import cv2
import numpy as np

input_image = cv2.imread("apple.png")

# First create an image the same size as our input
blank_image = np.zeros((input_image.shape), np.uint8) # np.zeros คือ สร้าง array ที่เต็มไปด้วยเลข 0

# give it a green square
blank_image[100:200,100:200,1]=100;

# add the two images together (unsafe) คล้าย ๆ รวม layer ใน photoshop
#new_image = blank_image + input_image

# add the two images together (safe) คล้าย ๆ รวม layer ใน photoshop 
# โดยใน cv2.add() จะมีการป้องกันไม่ให้ range ของรูปเกินกำหนด
new_image = cv2.add(blank_image,input_image)

cv2.imshow("result",new_image)
cv2.waitKey(0)

-1

In [25]:
flipped_code_0 = cv2.flip(input_image,0) # vertical flip
flipped_code_1 = cv2.flip(input_image,1) # horizontal flip
transposed = cv2.transpose(input_image) # Swap axis

### Image denoising (Noise reduction)

● Average filtering:
> เอา pixel ข้าง ๆ มาบวกกับ pixel ข้างเคียงแล้วจะเฉลี่ยให้ค่าสีเท่ากัน (เบลอเท่า ๆ กัน)

> void blur(InputArray src, OutputArray dst, parameters)

> void boxFilter(InputArray src, OutputArray dst, parameters)

● Gaussian filtering:
> นิยมใช้มาก

> จะหาความน่าจะเป็นของรูปว่าในระหว่าง pixel กับ pixel ข้าง ๆ เป็นยังไง (รูประฆังคว่ำ) ทำให้ตรงกลางจะเบลอมาก ตรงปลายจะเบลอน้อย

> void gaussianBlur(InputArray src, OutputArray dst, parameters)

● Bilateral filtering:
> เบลอแบบเอา pixel ทั้งหมดมาเบลอร่วมกัน โดยที่ยังคงสภาพของ surface ไว้

> void bilateralFilter(InputArray src, OutputArray dst, parameters)

● Median filtering:
> เบลอพื้นผิว มักใช้กำจัด noise ที่อยู่บน surface

> void medianBlur(InputArray src, OutputArray dst, parameters)

#### - ภาพสีเดิม

In [26]:
import cv2
 
# Reading the image
image = cv2.imread('apple.png')
 
# Showing the image
cv2.imshow('Original', image)

# Applying the filter
smoothimg = cv2.blur(image, (5, 5))
cv2.imshow('AvarageBlur', smoothimg)

smoothimg = cv2.GaussianBlur(image, (5, 5), 0)
cv2.imshow('GaussianBlur', smoothimg)

smoothimg = cv2.bilateralFilter(image, 5, 75, 75)
cv2.imshow('bilateralFilter', smoothimg)

smoothimg = cv2.medianBlur(image, 5)
cv2.imshow('medianBlur', smoothimg)

 
cv2.waitKey()
cv2.destroyAllWindows()

### Image Thresholding

Image Thresholding คือ เทคนิคตัดขอบของภาพ

**Type**

● cv2.THRESH_BINARY

● cv2.THRESH_BINARY_INV

● cv2.THRESH_TRUNC

● cv2.THRESH_TOZERO

● cv2.THRESH_TOZERO_INV

In [27]:
import cv2
 
# Reading the image
image = cv2.imread('apple.png',cv2.IMREAD_GRAYSCALE) # เปลี่ยนเป็นขาวดำ
 
# Showing the image
cv2.imshow('Original', image)

# Applying the threshold
# โดยเราตั้ง threshold อยู่ที่ 127 แล้ว maximum value อยู่ที่ 255
ret,thresh1 = cv2.threshold(image,127,255,cv2.THRESH_BINARY) # ถ้าค่า pixel ไหนเกิน 127 จะ set เป็น 255 หรือสีขาว เลย 
cv2.imshow('THRESH_BINARY', thresh1)

ret,thresh2 = cv2.threshold(image,127,255,cv2.THRESH_BINARY_INV) # INV คือ invert 
cv2.imshow('THRESH_BINARY_INV', thresh2)

ret,thresh3 = cv2.threshold(image,127,255,cv2.THRESH_TRUNC) # ถ้าค่าไหนเกิน 127 ก็ set เป็นค่านั้นเลย ส่วนค่าไหนไม่ถึงก็คงค่าเดิมไว้
cv2.imshow('THRESH_TRUNC', thresh3)

ret,thresh4 = cv2.threshold(image,127,255,cv2.THRESH_TOZERO) # ถ้าค่าไหนต่ำกว่า 127 ก็ set ค่านั้นเป็น 0 หรือสีดำเลย ส่วนค่าไหนสูงกว่าจะเป็นค่าเดิม
cv2.imshow('THRESH_TOZERO', thresh4)

ret,thresh5 = cv2.threshold(image,127,255,cv2.THRESH_TOZERO_INV) # INV คือ invert 
cv2.imshow('THRESH_TOZERO_INV', thresh5)
 
cv2.waitKey()
cv2.destroyAllWindows()

### Morphology Operations

Morphology คือการเปลี่ยนรูปแบบในต่างไปจากเดิม 

ในเชิง image processing จะหมายถึงให้รูปเปลี่ยนแปลง เช่น รูปร่างเปลี่ยน เส้นขอบชัดเจน เป็นต้น มักใช้ให้เส้นขอบของวัตถุชัดเจนขึ้น

**Type ที่มักใช้บ่อย** 

● cv2.MORPH_CLOSE

● cv2.MORPH_OPEN

● cv2.MORPH_GRADIENT

● cv2.MORPH_TOPHAT

● cv2.MORPH_BLACKHAT

In [28]:
import cv2
 
# Reading the image
image = cv2.imread('morph.png',cv2.IMREAD_GRAYSCALE) # เปลี่ยนเป็นขาวดำ
 
# Showing the image
cv2.imshow('Original', image)

# Applying the morph
morph = cv2.dilate(image,(5,5),iterations = 3) # เพิ่มขอบให้ใหญ่ขึ้น
cv2.imshow('dilate', morph)

morph = cv2.erode(image,(5,5),iterations = 3) # ลดขอบให้เล็กลง
cv2.imshow('erode', morph)

morph = cv2.morphologyEx(image, cv2.MORPH_OPEN, (5,5)) # ช่วยอุดรูรั่วขาว ๆ ในภาพ
cv2.imshow('MORPH_OPEN', morph)

morph = cv2.morphologyEx(image, cv2.MORPH_CLOSE, (5,5)) # ช่วยอุดรูรั่วดำ ๆ ในภาพ
cv2.imshow('MORPH_CLOSE', morph)

morph = cv2.morphologyEx(image, cv2.MORPH_GRADIENT, (5,5)) # จะรวมกันระหว่าง MORPH_OPEN และ MORPH_CLOSE โดยจะได้ขอบของวัตถุนั้น ๆ 
cv2.imshow('MORPH_GRADIENT', morph)
 
cv2.waitKey()
cv2.destroyAllWindows()